services:
  pablesite:
    image: ${PABLESITE_IMAGE:-pablesite:latest}
    container_name: pablesite
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: "true"
      traefik.http.routers.pablesite.rule: "Host(`${PABLESITE_HOST:-pablesite.es}`)"
      traefik.docker.network: "${TRAEFIK_NETWORK:-proxy}"
      traefik.http.routers.pablesite.entrypoints: "${TRAEFIK_ENTRYPOINTS:-web}"
      traefik.http.services.pablesite.loadbalancer.server.port: "8080"

networks:
  proxy:
    external: true
    name: ${TRAEFIK_NETWORK:-proxy}
